export const localeCodes = ['en', 'hi', 'or', 'ta', 'te', 'kn', 'bn'] as const;
export type Locale = typeof localeCodes[number];

export const localeNames: Record<Locale, string> = {
  en: 'English', hi: 'हिन्दी', or: 'ଓଡ଼ିଆ', ta: 'தமிழ்', te: 'తెలుగు', kn: 'ಕನ್ನಡ', bn: 'বাংলা'
};

export const localeCopy = {
  en: { eyebrow: 'Made for people who were never taught this.', title: 'Use AI confidently. Stay safe online.', intro: 'Short lessons that explain WhatsApp, UPI, Google, and ChatGPT the way someone should have, the day you got a smartphone.', choose: 'Where do you want to start?', topics: 'Browse by topic', forYou: 'Use this in the life you already have', learn: 'Use AI', learnDesc: 'Five short lessons: what it is, how to ask, how to check', safety: 'Stay safe online', safetyDesc: 'Seven lessons: passwords, money on your phone, fake links', guides: 'Apply it', guidesDesc: 'A path for home, work, school, or the job you already do', help: 'Something went wrong?', helpDesc: 'You are not the first. Take the next right step now', home: 'Home', fallback: 'This lesson is being translated. The English version is shown for now.' },
  hi: { eyebrow: 'उन लोगों के लिए जिन्हें यह कभी सिखाया नहीं गया।', title: 'AI से काम लें। ऑनलाइन सुरक्षित रहें।', intro: 'WhatsApp, UPI, Google, ChatGPT — स्मार्टफोन आने के दिन किसी ने समझाया होता, तो ये छोटे पाठ वही बात हैं।', choose: 'कहाँ से शुरू करना है?', topics: 'विषय के अनुसार', forYou: 'इसे अपनी असली ज़िंदगी में लगाएँ', learn: 'AI से काम लें', learnDesc: 'पाँच छोटे पाठ: यह है क्या, कैसे पूछें, कैसे जाँचें', safety: 'ऑनलाइन सुरक्षित रहें', safetyDesc: 'सात पाठ: पासवर्ड, फ़ोन पर पैसे, नकली लिंक', guides: 'ज़िंदगी में लगाएँ', guidesDesc: 'घर, काम, स्कूल, या जो काम आप पहले से करते हैं', help: 'कुछ गड़बड़ हो गई?', helpDesc: 'आप पहले नहीं हैं। अगला सही कदम अभी उठाएँ', home: 'होम', fallback: 'इस पाठ का अनुवाद हो रहा है। अभी अंग्रेज़ी संस्करण दिखाया गया है।' },
  or: { eyebrow: 'ଯେଉଁମାନଙ୍କୁ ଏହା କେବେ ଶିଖାଯାଇ ନାହିଁ, ସେମାନଙ୍କ ପାଇଁ।', title: 'AIରେ କାମ ଧରନ୍ତୁ। ଅନଲାଇନ୍‌ରେ ସୁରକ୍ଷିତ ରୁହନ୍ତୁ।', intro: 'WhatsApp, UPI, Google, ChatGPT — ସ୍ମାର୍ଟଫୋନ୍ ଆସିବା ଦିନ କେହି ବୁଝାଇଥାନ୍ତେ, ଏହି ଛୋଟ ପାଠ ସେହି କଥା।', choose: 'କେଉଁଠୁ ଆରମ୍ଭ କରିବେ?', topics: 'ବିଷୟ ଅନୁସାରେ', forYou: 'ଆପଣଙ୍କ ଚାଲୁଥିବା ଜୀବନରେ ଲଗାନ୍ତୁ', learn: 'AIରେ କାମ ଧରନ୍ତୁ', learnDesc: 'ପାଞ୍ଚଟି ଛୋଟ ପାଠ: ଏହା କ’ଣ, କିପରି ପଚାରିବେ, କିପରି ଯାଞ୍ଚ କରିବେ', safety: 'ଅନଲାଇନ୍‌ରେ ସୁରକ୍ଷିତ ରୁହନ୍ତୁ', safetyDesc: 'ସାତଟି ପାଠ: ପାସୱାର୍ଡ, ଫୋନ୍‌ରେ ଟଙ୍କା, ନକଲି ଲିଙ୍କ୍', guides: 'ଜୀବନରେ ଲଗାନ୍ତୁ', guidesDesc: 'ଘର, କାମ, ସ୍କୁଲ୍, କିମ୍ବା ଆପଣ କରୁଥିବା ଧନ୍ଦା', help: 'କିଛି ଗଡ଼ବଡ଼ ହେଲା?', helpDesc: 'ଆପଣ ପ୍ରଥମ ନୁହଁନ୍ତି। ପରବର୍ତ୍ତୀ ସଠିକ୍ ପଦକ୍ଷେପ ଏବେ ନିଅନ୍ତୁ', home: 'ହୋମ୍', fallback: 'ଏହି ପାଠର ଅନୁବାଦ ଚାଲିଛି। ବର୍ତ୍ତମାନ ଇଂରାଜୀ ସଂସ୍କରଣ ଦେଖାଯାଉଛି।' },
  ta: { eyebrow: 'இதை யாரும் சொல்லித் தராதவர்களுக்காக.', title: 'AI-ஐ நம்பிக்கையோடு பயன்படுத்துங்கள். இணையத்தில் பாதுகாப்பாக இருங்கள்.', intro: 'WhatsApp, UPI, Google, ChatGPT — போன் வந்த நாளில் யாராவது இப்படிச் சொல்லியிருக்க வேண்டும். அந்தச் சிறிய பாடங்கள்தான் இவை.', choose: 'எங்கிருந்து தொடங்கலாம்?', topics: 'தலைப்பு வாரியாக', forYou: 'நீங்கள் வாழும் வாழ்க்கையிலேயே இதைப் பயன்படுத்துங்கள்', learn: 'AI பயன்படுத்துங்கள்', learnDesc: 'ஐந்து சிறிய பாடங்கள்: இது என்ன, எப்படிக் கேட்பது, எப்படிச் சரிபார்ப்பது', safety: 'இணையத்தில் பாதுகாப்பு', safetyDesc: 'ஏழு பாடங்கள்: கடவுச்சொல், போனில் பணம், போலி இணைப்புகள்', guides: 'வாழ்க்கையில் பயன்படுத்துங்கள்', guidesDesc: 'வீடு, வேலை, பள்ளி, அல்லது நீங்கள் ஏற்கனவே செய்யும் வேலை', help: 'ஏதோ தவறாகிவிட்டதா?', helpDesc: 'இது உங்களுக்கு மட்டும் நடக்கவில்லை. அடுத்த சரியான அடியை இப்போதே எடுங்கள்', home: 'முகப்பு', fallback: 'இந்தப் பாடம் மொழிபெயர்க்கப்படுகிறது. இப்போது ஆங்கிலப் பதிப்பு காட்டப்படுகிறது.' },
  te: { eyebrow: 'ఇది ఎవరూ నేర్పని వాళ్ల కోసం.', title: 'AIతో పని చేయండి. ఆన్‌లైన్‌లో సురక్షితంగా ఉండండి.', intro: 'WhatsApp, UPI, Google, ChatGPT — ఫోన్ వచ్చిన రోజు ఎవరైనా ఇలా చెప్పి ఉండాల్సింది. ఆ చిన్న పాఠాలే ఇవి.', choose: 'ఎక్కడ నుంచి మొదలుపెట్టాలి?', topics: 'అంశాల వారీగా', forYou: 'మీరు ఇప్పటికే జీవిస్తున్న జీవితంలో దీన్ని వాడండి', learn: 'AIతో పని చేయండి', learnDesc: 'ఐదు చిన్న పాఠాలు: ఇది ఏమిటి, ఎలా అడగాలి, ఎలా సరిచూడాలి', safety: 'ఆన్‌లైన్‌లో సురక్షితంగా ఉండండి', safetyDesc: 'ఏడు పాఠాలు: పాస్‌వర్డ్, ఫోన్‌లో డబ్బు, నకిలీ లింకులు', guides: 'జీవితంలో వాడండి', guidesDesc: 'ఇల్లు, పని, స్కూలు, లేదా మీరు ఇప్పటికే చేస్తున్న పని', help: 'ఏదో తప్పు జరిగిందా?', helpDesc: 'మీరొక్కరే కాదు. తర్వాతి సరైన అడుగు ఇప్పుడే వేయండి', home: 'హోమ్', fallback: 'ఈ పాఠం అనువదించబడుతోంది. ప్రస్తుతం ఆంగ్ల వెర్షన్ చూపబడుతోంది.' },
  kn: { eyebrow: 'ಇದನ್ನು ಯಾರೂ ಕಲಿಸದಿದ್ದವರಿಗಾಗಿ.', title: 'AI ಉಪಯೋಗಿಸಿ. ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಸುರಕ್ಷಿತರಾಗಿ.', intro: 'WhatsApp, UPI, Google, ChatGPT — ಫೋನ್ ಬಂದ ದಿನ ಯಾರಾದರೂ ಹೀಗೆ ಹೇಳಿರಬೇಕಿತ್ತು. ಆ ಚಿಕ್ಕ ಪಾಠಗಳೇ ಇವು.', choose: 'ಎಲ್ಲಿಂದ ಶುರು ಮಾಡುವುದು?', topics: 'ವಿಷಯದ ಪ್ರಕಾರ', forYou: 'ನೀವು ಈಗಾಗಲೇ ನಡೆಸುತ್ತಿರುವ ಜೀವನದಲ್ಲಿ ಇದನ್ನು ಬಳಸಿ', learn: 'AI ಬಳಸಿ', learnDesc: 'ಐದು ಚಿಕ್ಕ ಪಾಠ: ಇದು ಏನು, ಹೇಗೆ ಕೇಳುವುದು, ಹೇಗೆ ಪರಿಶೀಲಿಸುವುದು', safety: 'ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿರಿ', safetyDesc: 'ಏಳು ಪಾಠ: ಪಾಸ್‌ವರ್ಡ್, ಫೋನ್‌ನಲ್ಲಿ ಹಣ, ನಕಲಿ ಲಿಂಕ್', guides: 'ಜೀವನದಲ್ಲಿ ಬಳಸಿ', guidesDesc: 'ಮನೆ, ಕೆಲಸ, ಶಾಲೆ, ಅಥವಾ ನೀವು ಈಗಾಗಲೇ ಮಾಡುವ ಕೆಲಸ', help: 'ಏನಾದರೂ ತಪ್ಪಾಗಿದೆಯೇ?', helpDesc: 'ನೀವು ಮೊದಲಿಗರಲ್ಲ. ಮುಂದಿನ ಸರಿಯಾದ ಹೆಜ್ಜೆ ಈಗ ಇಡಿ', home: 'ಮುಖಪುಟ', fallback: 'ಈ ಪಾಠವನ್ನು ಅನುವಾದಿಸಲಾಗುತ್ತಿದೆ. ಸದ್ಯಕ್ಕೆ ಇಂಗ್ಲಿಷ್ ಆವೃತ್ತಿಯನ್ನು ತೋರಿಸಲಾಗಿದೆ.' },
  bn: { eyebrow: 'যাদের কখনো এসব শেখানো হয়নি, তাদের জন্য।', title: 'AI দিয়ে কাজ করুন। অনলাইনে নিরাপদ থাকুন।', intro: 'WhatsApp, UPI, Google, ChatGPT — ফোন আসার দিন কেউ যদি বুঝিয়ে দিত, এই ছোট পাঠগুলো সেই কথাই।', choose: 'কোথা থেকে শুরু করবেন?', topics: 'বিষয় অনুযায়ী', forYou: 'যে জীবন চলছে, সেখানেই এটা লাগান', learn: 'AI দিয়ে কাজ করুন', learnDesc: 'পাঁচটি ছোট পাঠ: এটা কী, কীভাবে জিজ্ঞেস করবেন, কীভাবে যাচাই করবেন', safety: 'অনলাইনে নিরাপদ থাকুন', safetyDesc: 'সাতটি পাঠ: পাসওয়ার্ড, ফোনে টাকা, নকল লিংক', guides: 'জীবনে লাগান', guidesDesc: 'ঘর, কাজ, স্কুল, বা যে কাজ আপনি আগে থেকেই করেন', help: 'কিছু গন্ডগোল হয়েছে?', helpDesc: 'আপনি প্রথম নন। পরের সঠিক পদক্ষেপ এখনই নিন', home: 'হোম', fallback: 'এই পাঠটি অনুবাদ করা হচ্ছে। আপাতত ইংরেজি সংস্করণ দেখানো হয়েছে।' }
} satisfies Record<Locale, Record<string, string>>;

export function localePath(locale: Locale, path = '/') {
  const clean = path.startsWith('/') ? path : `/${path}`;
  return locale === 'en' ? clean : `/${locale}${clean}`;
}
