export const localeCodes = ['en', 'hi', 'or', 'ta', 'te', 'kn', 'bn'] as const;
export type Locale = typeof localeCodes[number];

export const localeNames: Record<Locale, string> = {
  en: 'English', hi: 'हिन्दी', or: 'ଓଡ଼ିଆ', ta: 'தமிழ்', te: 'తెలుగు', kn: 'ಕನ್ನಡ', bn: 'বাংলা'
};

export const localeCopy = {
  en: { eyebrow: 'Simple language. Practical help.', title: 'Use AI confidently. Stay safe online.', intro: 'Short, useful lessons for work, home, and everyday life.', choose: 'What do you want to learn?', topics: 'Browse by topic', forYou: 'Guides for your work and life', learn: 'Use AI', learnDesc: 'Write, understand, translate, and learn', safety: 'Stay safe online', safetyDesc: 'Spot scams and protect your information', guides: 'Guides for you', guidesDesc: 'Practical paths for your work and life', help: 'Something went wrong?', helpDesc: 'Stay calm and take the right steps now', home: 'Home', fallback: 'This lesson is being translated. The English version is shown for now.' },
  hi: { eyebrow: 'आसान भाषा। काम की जानकारी।', title: 'AI का सही उपयोग करें। ऑनलाइन सुरक्षित रहें।', intro: 'काम, घर और रोज़मर्रा की ज़िंदगी के लिए छोटे और उपयोगी पाठ।', choose: 'आप क्या सीखना चाहते हैं?', topics: 'विषय के अनुसार', forYou: 'आपके काम और जीवन के लिए', learn: 'AI का उपयोग करें', learnDesc: 'लिखें, समझें, अनुवाद करें और सीखें', safety: 'ऑनलाइन सुरक्षित रहें', safetyDesc: 'धोखाधड़ी पहचानें और अपनी जानकारी बचाएँ', guides: 'आपके लिए गाइड', guidesDesc: 'काम और जीवन के लिए उपयोगी रास्ते', help: 'कुछ गलत हो गया?', helpDesc: 'शांत रहें और अभी सही कदम उठाएँ', home: 'होम', fallback: 'इस पाठ का अनुवाद हो रहा है। अभी अंग्रेज़ी संस्करण दिखाया गया है।' },
  or: { eyebrow: 'ସରଳ ଭାଷା। ବ୍ୟବହାରିକ ସାହାଯ୍ୟ।', title: 'ଆତ୍ମବିଶ୍ୱାସରେ AI ବ୍ୟବହାର କରନ୍ତୁ। ଅନଲାଇନ୍‌ରେ ସୁରକ୍ଷିତ ରୁହନ୍ତୁ।', intro: 'କାମ, ଘର ଓ ଦୈନନ୍ଦିନ ଜୀବନ ପାଇଁ ଛୋଟ ଉପଯୋଗୀ ପାଠ।', choose: 'ଆପଣ କ’ଣ ଶିଖିବାକୁ ଚାହାନ୍ତି?', topics: 'ବିଷୟ ଅନୁସାରେ', forYou: 'ଆପଣଙ୍କ କାମ ଓ ଜୀବନ ପାଇଁ', learn: 'AI ବ୍ୟବହାର କରନ୍ତୁ', learnDesc: 'ଲେଖନ୍ତୁ, ବୁଝନ୍ତୁ, ଅନୁବାଦ କରନ୍ତୁ ଓ ଶିଖନ୍ତୁ', safety: 'ଅନଲାଇନ୍‌ରେ ସୁରକ୍ଷିତ ରୁହନ୍ତୁ', safetyDesc: 'ଠକେଇ ଚିହ୍ନନ୍ତୁ ଓ ସୂଚନା ସୁରକ୍ଷିତ ରଖନ୍ତୁ', guides: 'ଆପଣଙ୍କ ପାଇଁ ଗାଇଡ୍', guidesDesc: 'କାମ ଓ ଜୀବନ ପାଇଁ ବ୍ୟବହାରିକ ପଥ', help: 'କିଛି ଭୁଲ ହୋଇଗଲା?', helpDesc: 'ଶାନ୍ତ ରୁହନ୍ତୁ ଓ ଏବେ ଠିକ୍ ପଦକ୍ଷେପ ନିଅନ୍ତୁ', home: 'ହୋମ୍', fallback: 'ଏହି ପାଠର ଅନୁବାଦ ଚାଲିଛି। ବର୍ତ୍ତମାନ ଇଂରାଜୀ ସଂସ୍କରଣ ଦେଖାଯାଉଛି।' },
  ta: { eyebrow: 'எளிய மொழி. நடைமுறை உதவி.', title: 'AI-ஐ நம்பிக்கையுடன் பயன்படுத்துங்கள். இணையத்தில் பாதுகாப்பாக இருங்கள்.', intro: 'வேலை, வீடு மற்றும் அன்றாட வாழ்க்கைக்கான சிறிய பயனுள்ள பாடங்கள்.', choose: 'நீங்கள் என்ன கற்க விரும்புகிறீர்கள்?', topics: 'தலைப்பு வாரியாக', forYou: 'உங்கள் வேலைக்கும் வாழ்க்கைக்கும்', learn: 'AI பயன்படுத்துங்கள்', learnDesc: 'எழுதுங்கள், புரிந்துகொள்ளுங்கள், மொழிபெயருங்கள், கற்றுக்கொள்ளுங்கள்', safety: 'இணையத்தில் பாதுகாப்பு', safetyDesc: 'மோசடிகளை அறிந்து தகவல்களைப் பாதுகாக்குங்கள்', guides: 'உங்களுக்கான வழிகாட்டிகள்', guidesDesc: 'வேலை மற்றும் வாழ்க்கைக்கான நடைமுறை பாதைகள்', help: 'ஏதாவது தவறாகிவிட்டதா?', helpDesc: 'அமைதியாக இருந்து சரியான நடவடிக்கையை எடுங்கள்', home: 'முகப்பு', fallback: 'இந்தப் பாடம் மொழிபெயர்க்கப்படுகிறது. இப்போது ஆங்கிலப் பதிப்பு காட்டப்படுகிறது.' },
  te: { eyebrow: 'సులభమైన భాష. ఉపయోగకరమైన సహాయం.', title: 'AIని నమ్మకంగా ఉపయోగించండి. ఆన్‌లైన్‌లో సురక్షితంగా ఉండండి.', intro: 'పని, ఇల్లు మరియు రోజువారీ జీవితానికి చిన్న ఉపయోగకరమైన పాఠాలు.', choose: 'మీరు ఏమి నేర్చుకోవాలనుకుంటున్నారు?', topics: 'అంశాల వారీగా', forYou: 'మీ పని మరియు జీవితం కోసం', learn: 'AI ఉపయోగించండి', learnDesc: 'రాయండి, అర్థం చేసుకోండి, అనువదించండి, నేర్చుకోండి', safety: 'ఆన్‌లైన్‌లో సురక్షితంగా ఉండండి', safetyDesc: 'మోసాలను గుర్తించి మీ సమాచారాన్ని కాపాడుకోండి', guides: 'మీ కోసం మార్గదర్శకాలు', guidesDesc: 'పని మరియు జీవితానికి ఉపయోగకరమైన మార్గాలు', help: 'ఏదైనా తప్పు జరిగిందా?', helpDesc: 'ప్రశాంతంగా ఉండి సరైన చర్య తీసుకోండి', home: 'హోమ్', fallback: 'ఈ పాఠం అనువదించబడుతోంది. ప్రస్తుతం ఆంగ్ల వెర్షన్ చూపబడుతోంది.' },
  kn: { eyebrow: 'ಸರಳ ಭಾಷೆ. ಪ್ರಾಯೋಗಿಕ ಸಹಾಯ.', title: 'AI ಅನ್ನು ಆತ್ಮವಿಶ್ವಾಸದಿಂದ ಬಳಸಿ. ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿರಿ.', intro: 'ಕೆಲಸ, ಮನೆ ಮತ್ತು ದೈನಂದಿನ ಜೀವನಕ್ಕಾಗಿ ಚಿಕ್ಕ ಉಪಯುಕ್ತ ಪಾಠಗಳು.', choose: 'ನೀವು ಏನು ಕಲಿಯಲು ಬಯಸುತ್ತೀರಿ?', topics: 'ವಿಷಯದ ಪ್ರಕಾರ', forYou: 'ನಿಮ್ಮ ಕೆಲಸ ಮತ್ತು ಜೀವನಕ್ಕಾಗಿ', learn: 'AI ಬಳಸಿ', learnDesc: 'ಬರೆಯಿರಿ, ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ, ಅನುವಾದಿಸಿ ಮತ್ತು ಕಲಿಯಿರಿ', safety: 'ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿರಿ', safetyDesc: 'ವಂಚನೆ ಗುರುತಿಸಿ ಮತ್ತು ಮಾಹಿತಿ ರಕ್ಷಿಸಿ', guides: 'ನಿಮಗಾಗಿ ಮಾರ್ಗದರ್ಶಿಗಳು', guidesDesc: 'ಕೆಲಸ ಮತ್ತು ಜೀವನಕ್ಕೆ ಪ್ರಾಯೋಗಿಕ ಮಾರ್ಗಗಳು', help: 'ಏನಾದರೂ ತಪ್ಪಾಗಿದೆಯೇ?', helpDesc: 'ಶಾಂತವಾಗಿರಿ ಮತ್ತು ಸರಿಯಾದ ಕ್ರಮ ಕೈಗೊಳ್ಳಿ', home: 'ಮುಖಪುಟ', fallback: 'ಈ ಪಾಠವನ್ನು ಅನುವಾದಿಸಲಾಗುತ್ತಿದೆ. ಸದ್ಯಕ್ಕೆ ಇಂಗ್ಲಿಷ್ ಆವೃತ್ತಿಯನ್ನು ತೋರಿಸಲಾಗಿದೆ.' },
  bn: { eyebrow: 'সহজ ভাষা। ব্যবহারিক সহায়তা।', title: 'আত্মবিশ্বাসের সঙ্গে AI ব্যবহার করুন। অনলাইনে নিরাপদ থাকুন।', intro: 'কাজ, ঘর এবং দৈনন্দিন জীবনের জন্য ছোট ও কার্যকর পাঠ।', choose: 'আপনি কী শিখতে চান?', topics: 'বিষয় অনুযায়ী', forYou: 'আপনার কাজ ও জীবনের জন্য', learn: 'AI ব্যবহার করুন', learnDesc: 'লিখুন, বুঝুন, অনুবাদ করুন এবং শিখুন', safety: 'অনলাইনে নিরাপদ থাকুন', safetyDesc: 'প্রতারণা চিনুন এবং তথ্য সুরক্ষিত রাখুন', guides: 'আপনার জন্য নির্দেশিকা', guidesDesc: 'কাজ ও জীবনের ব্যবহারিক পথ', help: 'কিছু ভুল হয়েছে?', helpDesc: 'শান্ত থাকুন এবং এখনই সঠিক পদক্ষেপ নিন', home: 'হোম', fallback: 'এই পাঠটি অনুবাদ করা হচ্ছে। আপাতত ইংরেজি সংস্করণ দেখানো হয়েছে।' }
} satisfies Record<Locale, Record<string, string>>;

export function localePath(locale: Locale, path = '/') {
  const clean = path.startsWith('/') ? path : `/${path}`;
  return locale === 'en' ? clean : `/${locale}${clean}`;
}
